//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int OrderQty { get; set; }
        public double OrderBill { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Order_Unitprice { get; set; }
        public int NewspaperId { get; set; }
        public int InvoiceId { get; set; }
    
        public virtual Newspaper Newspaper { get; set; }
        public virtual tbl_invoice tbl_invoice { get; set; }
    }
}
